#!/bin/bash -x
#
# Quirinux-DEB Postinstall 1.0
#
# Autor: Charlie Martínez
#


if [ -e "sources.list" ]; then

sudo mv /etc/apt/sources.list /etc/apt/sources.list.bk

fi

if [ -e "repo-config" ]; then

sudo mv /usr/local/bin/repo-config /usr/local/bin/repo-config.bk

fi
